### ISSUE TITLE
Faster Payment flow?

### ISSUE THREAD

**Issue by loicortola** [sumup/Android-MerchantSDK#6]
The Payment flow is the following:
0- Enter amount, setup payment, Launch the SumUpActivity
1- Authenticate (2s)
2- Switch the SumUp Pad on, wait for it to boot up (20s)
3- User enters his pin, validates (5s)
4- Payment is processed (2s)
5- SumUp Pad is automatically shut down 
6- Activity saying if we want to send receipt or not (2s)
7- ResultActivity (2s), start over?

The payment process takes approximately 30-35 seconds, and the number of steps between one payment and the next one is 8.

The most time-consuming step is that we have to turn the SumUp Pad on every time we make payment. Is there a configuration parameter to be set on the Pad to keep it on wake? (I may have been missing something :D)

Last, but not least, I think steps 7 and 8 could be merged by adding a button "make other payment". This would send an extra info to the result activity telling it it wants another payment. Of course, not every vendor may want this button, it should be configured somewhere (styles and button visibility?)

The main use case for this is: how do we maintain an acceptable QoS when it is rush hour and I have to make 100s of payments?

**Comment by ultrah** [comment]
While I can see that is a valid request, this is very broad topic. I think its better if we discuss this via email.
